# Generated by Django 4.2.5 on 2023-12-06 14:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='message',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
