# Generated by Django 4.2.6 on 2023-10-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acts',
            name='image',
            field=models.FileField(blank=True, upload_to='acts_images/'),
        ),
    ]
