# Generated by Django 4.2.6 on 2023-12-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0002_acts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acts',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
